eidoo/hybrid-exchange-sdk

- CHANGELOG.md
- README.md
- examples/lib/pair/getFee.js
- src/lib/ExchangeApiLib/ExchangeApiLib.js
- src/services/PairService.js
- tests/factories/MockFeeFactory.js
- tests/unit/commands/createWalletCommand.test.js
- tests/unit/lib/ExchangeApiLib/ExchangeApiLib.test.js
- tests/unit/services/OrderService.test.js
- tests/unit/services/PairService.test.js
- tests/unit/services/TradingWalletService.test.js
#1 
Please run tests and check retrieve fee pair example in `/examples` dir.
> #1 retrieve pair fee

- CHANGELOG.md
- examples/lib/pair/getPrice.js
- src/lib/ExchangeApiLib/ExchangeApiLib.js
- src/services/PairService.js
- tests/factories/MockPairPriceFactory.js
- tests/unit/lib/ExchangeApiLib/ExchangeApiLib.test.js
- tests/unit/services/PairService.test.js
As a user I want to retrieve pair price. Resolves #3 .
Please run tests and check the example in `/examples`
> #3 Retrieve pair price

- examples/lib/tradingWallet/allowance/getAllowance.js
- examples/lib/tradingWallet/approve/approve.js
- examples/lib/tradingWallet/balances/getEthBalance.js
- examples/lib/tradingWallet/createWallet/createWallet.js
- examples/lib/tradingWallet/depositEth/depositEther.js
- examples/lib/tradingWallet/depositToken/depositToken.js
- examples/lib/tradingWallet/getAddress/getAddress.js
- examples/lib/tradingWallet/withdraw/withdraw.js
- src/commands/commandList.js
- src/factories/Erc20TokenServiceBuilder.js
- src/factories/TradingWalletServiceBuilder.js
- src/factories/index.js
- src/services/Erc20TokenService.js
- src/services/TradingWalletService.js
- tests/unit/commands/createWalletCommand.test.js
- tests/unit/commands/getAddressCommand.test.js
- tests/unit/services/TradingWalletService.test.js
Resolves #9 
Check the examples with the new factories implemented.
> 9 add service factories

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/refactor.md
Resolves #17  
Add specific template for:
- bug report
- feature request
- refactor
> Update issue templates

- CHANGELOG.md
- src/cli/tws/withdraw.js
- src/commands/ABaseCommand.js
- src/commands/GetAddressCommand.js
- src/commands/OrderSignCommand.js
- src/commands/WithdrawCommand.js
- src/commands/commandList.js
- src/factories/BaseTransactionBuilder.js
- src/factories/TradingWalletTransactionBuilder.js
- src/lib/TransactionLib/TransactionLib.js
- src/models/Transaction.js
- src/validators/PrivateKeyValidator.js
- src/validators/WithdrawCommandValidator.js
- tests/unit/commands/createWalletCommand.test.js
- tests/unit/commands/signCommand.test.js
- tests/unit/commands/withdrawTokenCommand.test.js
Resolves #13 
Please use cli to:
- get the Transaction object draft of withdraw transaction.
- get the signed transaction data.
- execute withdraw.
> 13 withdraw commands

- CHANGELOG.md
- src/cli/tws/deposit-eth.js
- src/commands/DepositEthCommand.js
- src/commands/commandList.js
- src/commands/index.js
- src/validators/DepositEthCommandValidator.js
- tests/unit/commands/depositEthCommand.test.js
Resolves #15 
Allows to deposit ETH from an EAO to a trading wallet SC.
> Add CLI Deposit ETH command

- CHANGELOG.md
- README.md
- src/cli/tws/approve.js
- src/commands/ApproveCommand.js
- src/commands/commandList.js
- src/services/BaseTransactionService.js
- src/services/TradingWalletService.js
- src/validators/ApproveCommandValidator.js
- tests/unit/commands/approveCommand.test.js
Resolves #18 
Run command and please check tests.
> Add approve token command

- CHANGELOG.md
- src/commands/ApproveCommand.js
- src/validators/ApproveCommandValidator.js
- tests/unit/commands/approveCommand.test.js
> Fix approve command tests

- CHANGELOG.md
- src/cli/tks.js
- src/cli/tks/get-allowance.js
- src/commands/GetAllowanceCommand.js
- src/commands/commandList.js
- src/validators/GetAllowanceCommandValidator.js
- tests/unit/commands/getAllowanceCommand.test.js
Resolves #24 
Run tests and try to use allowance command.
> Add get allowance command

- CHANGELOG.md
- src/cli/tws/get-balance.js
- src/commands/GetAddressCommand.js
- src/commands/GetBalanceCommand.js
- src/commands/commandList.js
- src/commands/index.js
- src/validators/GetBalanceCommandValidator.js
- src/validators/GetTradingWalletBalanceCommandValidator.js
- tests/unit/commands/getTradingWalletBalanceCommand.test.js
Resolves #20 .
Allows to check an asset balance from a trading wallet point of view.
> Add trading wallet balance command

- CHANGELOG.md
- src/cli/os/cancel.js
- src/commands/OrderCancelCommand.js
- src/commands/commandList.js
- src/lib/ExchangeApiLib/ExchangeApiLib.js
- src/lib/ExchangeApiLib/ExchangeApiLibError.js
- src/validators/OrderCancelCommandValidator.js
- tests/unit/commands/orderCancelCommand.test.js
- tests/unit/services/OrderService.test.js
Resolves #26 
Run tests and try to run command for the following cases:
> Cancel order

- .circleci/config.yml
- CHANGELOG.md
- README.md
> Add circle ci

- CHANGELOG.md
- README.md
- src/cli/tws/deposit-token.js
- src/commands/DepositTokenCommand.js
- src/commands/commandList.js
- src/commands/index.js
- src/validators/DepositTokenCommandValidator.js
- tests/unit/commands/depositEthCommand.test.js
- tests/unit/commands/depositTokenCommand.test.js
> Add deposit token command

- CHANGELOG.md
- src/commands/commandList.js
- src/factories/commands/ApproveCommandBuilder.js
- src/factories/commands/CreateWalletCommandBuilder.js
- src/factories/commands/DepositEthCommandBuilder.js
- src/factories/commands/DepositTokenCommandBuilder.js
- src/factories/commands/GetAddressCommandBuilder.js
- src/factories/commands/GetAllowanceCommandBuilder.js
- src/factories/commands/GetBalanceCommandBuilder.js
- src/factories/commands/OrderCancelCommandBuilder.js
- src/factories/commands/OrderSignCommandBuilder.js
- src/factories/commands/WithdrawCommandBuilder.js
> Refactor adding command factories

- CHANGELOG.md
- src/cli/order/create.js
- src/commands/commandList.js
- src/commands/order/OrderCreateCommand.js
- src/factories/commands/order/OrderCreateCommandBuilder.js
- src/validators/commands/order/OrderCreateCommandValidator.js
- tests/unit/commands/orderCreateCommand.test.js
Resolves #46 
Try to create an order and check the folowing cases:
> Create order command

- src/factories/PrivateKeyServiceBuilder.js
- src/factories/commands/ehtereum-wallet/KeyStoreGenerateCommandBuilder.js
- src/factories/commands/order/OrderCancelCommandBuilder.js
- src/factories/commands/order/OrderCreateCommandBuilder.js
- src/factories/commands/order/OrderSignCommandBuilder.js
- src/factories/commands/token/ApproveCommandBuilder.js
- src/factories/commands/token/GetAllowanceCommandBuilder.js
- src/factories/commands/trading-wallet/CreateWalletCommandBuilder.js
- src/factories/commands/trading-wallet/DepositEthCommandBuilder.js
- src/factories/commands/trading-wallet/DepositTokenCommandBuilder.js
- src/factories/commands/trading-wallet/GetAddressCommandBuilder.js
- src/factories/commands/trading-wallet/GetBalanceCommandBuilder.js
- src/factories/commands/trading-wallet/WithdrawCommandBuilder.js
- src/services/PrivateKeyService.js
- tests/unit/commands/createWalletCommand.test.js
- tests/unit/commands/getAddressCommand.test.js
- tests/unit/commands/getTradingWalletBalanceCommand.test.js
- tests/unit/commands/signCommand.test.js
- tests/unit/services/PrivateKeyService.test.js
> 52 private key builder

- CHANGELOG.md
- src/config/index.js
> Fix config

- CHANGELOG.md
- src/commands/trading-wallet/GetBalanceCommand.js
- src/factories/commands/trading-wallet/GetBalanceCommandBuilder.js
- src/validators/commands/trading-wallet/GetBalanceCommandValidator.js
- tests/unit/commands/getTradingWalletBalanceCommand.test.js
> Remove private key dependencies from get balance command

- CHANGELOG.md
- src/commands/token/GetAllowanceCommand.js
- src/factories/commands/token/GetAllowanceCommandBuilder.js
- src/validators/commands/token/GetAllowanceCommandValidator.js
- tests/unit/commands/getAllowanceCommand.test.js
> Remove private key dependencies in get allowance command

- CHANGELOG.md
- src/commands/trading-wallet/GetAddressCommand.js
- src/factories/commands/trading-wallet/GetAddressCommandBuilder.js
- src/validators/commands/trading-wallet/GetAddressCommandValidator.js
- tests/unit/commands/getAddressCommand.test.js
> Remove private key parameter from get address command

- CHANGELOG.md
- src/commands/trading-wallet/DepositTokenCommand.js
- src/validators/commands/trading-wallet/DepositTokenCommandValidator.js
- tests/unit/commands/depositTokenCommand.test.js
Resolves #66 .
Refactor of the command using the keystore flow.
> Refactor deposit token command with keystore

- CHANGELOG.md
- src/commands/trading-wallet/CreateWalletCommand.js
- src/factories/commands/trading-wallet/CreateWalletCommandBuilder.js
- src/validators/commands/trading-wallet/CreateWalletCommandValidator.js
- tests/unit/commands/createWalletCommand.test.js
> Refactor create wallet command using keystore

- CHANGELOG.md
- src/commands/order/OrderSignCommand.js
- tests/unit/commands/signCommand.test.js
> Refactor order sign command with keystore

- CHANGELOG.md
- src/commands/order/OrderCreateCommand.js
- src/validators/commands/order/OrderCreateCommandValidator.js
- tests/unit/commands/orderCreateCommand.test.js
> Refactor order create command with keystore

- CHANGELOG.md
- src/commands/order/OrderCancelCommand.js
- src/validators/commands/order/OrderCancelCommandValidator.js
- tests/unit/commands/orderCancelCommand.test.js
> Refactor cancel order command with keystore

- CHANGELOG.md
- src/commands/ethereum-wallet/KeyStoreGenerateCommand.js
- src/commands/order/OrderCancelCommand.js
- src/commands/order/OrderCreateCommand.js
- src/commands/order/OrderSignCommand.js
- src/commands/token/ApproveCommand.js
- src/commands/trading-wallet/CreateWalletCommand.js
- src/commands/trading-wallet/DepositEthCommand.js
- src/commands/trading-wallet/DepositTokenCommand.js
- src/commands/trading-wallet/WithdrawCommand.js
- src/validators/commands/token/ApproveCommandValidator.js
- tests/unit/commands/approveCommand.test.js
> Refactor approve command with keystore

- CHANGELOG.md
- src/factories/commands/order/OrderCancelCommandBuilder.js
- src/factories/commands/order/OrderCreateCommandBuilder.js
- src/services/OrderService.js
- tests/unit/services/OrderService.test.js
Resolves #87 
Run tests and try to create/cancel an order.
> 87 refactor order service

- CHANGELOG.md
- src/cli/trading-wallet/update-exchange.js
- src/commands/commandList.js
- src/commands/trading-wallet/UpdateExchangeCommand.js
- src/factories/TradingWalletTransactionBuilder.js
- src/factories/commands/trading-wallet/UpdateExchangeCommandBuilder.js
- src/services/TradingWalletService.js
- src/validators/commands/trading-wallet/UpdateExchangeCommandValidator.js
- tests/unit/factories/TradingWalletTransactionBuilder.test.js
Resolves #93 .
Manually tested on Eidoo testnet.
> Add trading wallet update exchange feature

- CHANGELOG.md
- src/cli/trading-wallet/get-exchange.js
- src/commands/commandList.js
- src/commands/trading-wallet/GetExchangeCommand.js
- src/factories/TradingWalletTransactionBuilder.js
- src/factories/commands/trading-wallet/GetExchangeCommandBuilder.js
- src/services/TradingWalletService.js
- src/validators/commands/trading-wallet/GetExchangeCommandValidator.js
- tests/unit/factories/TradingWalletTransactionBuilder.test.js
Resolves #95 .
Manually tested on Eidoo testnet.
> Add trading wallet get-exchange feature

- CHANGELOG.md
- src/cli/trading-wallet/get-owner.js
- src/commands/commandList.js
- src/commands/trading-wallet/GetOwnerCommand.js
- src/factories/TradingWalletTransactionBuilder.js
- src/factories/commands/trading-wallet/GetOwnerCommandBuilder.js
- src/services/TradingWalletService.js
- src/validators/commands/trading-wallet/GetOwnerCommandValidator.js
- tests/unit/factories/TradingWalletTransactionBuilder.test.js
Resolve #97 .
Manually tested on Eidoo testnet.
> Add trading wallet get-owner feature

- examples/lib/tradingWallet/getExchange/getExchange.js
- examples/lib/tradingWallet/getOwner/getOwner.js
- examples/lib/tradingWallet/updateExchange/buildUpdateExchange.js
- examples/lib/tradingWallet/updateExchange/signDepositToken.js
- examples/lib/tradingWallet/updateExchange/updateExchange.js
Add trading wallet service samples about:
- get exchange
- update exchange
- get owner
> Add get/update exchange and get owner examples

- CHANGELOG.md
- package.json
- src/factories/Erc20TokenServiceBuilder.js
- yarn.lock
> Refactor erc20 token service builder

- CHANGELOG.md
- src/config/index.js
> Update exchange smart contract address (v2 => v3)
